export const fileIcons = {
    js: <i className="devicon-javascript-plain colored"></i>,
    ts: <i className="devicon-typescript-plain colored"></i>,
    jsx: <i className="devicon-react-original colored"></i>,
    tsx: <i className="devicon-react-original colored"></i>,
    html: <i className="devicon-html5-plain colored"></i>,
    css: <i className="devicon-css3-plain colored"></i>,
    py: <i className="devicon-python-plain colored"></i>,
    java: <i className="devicon-java-plain colored"></i>,
    rb: <i className="devicon-ruby-plain colored"></i>,
    php: <i className="devicon-php-plain colored"></i>,
    go: <i className="devicon-go-original-wordmark colored"></i>,
    swift: <i className="devicon-swift-plain colored"></i>,
    cpp: <i className="devicon-cplusplus-plain colored"></i>,
    c: <i className="devicon-c-plain colored"></i>,
    cs: <i className="devicon-csharp-plain colored"></i>,
    kotlin: <i className="devicon-kotlin-plain colored"></i>,
    dart: <i className="devicon-dart-plain colored"></i>,
    rust: <i className="devicon-rust-plain colored"></i>,
    scala: <i className="devicon-scala-plain colored"></i>,
    // Add more file types here
};